apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: mokhs00/boaz-k8s-sample-user
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "user-redis" # kubernetes internal DNS를 이용
            - name: REDIS_PORT
              value: "6379"

---

apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # 30080 port로 접근할 수 있도록 nodePort open
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-redis
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user-redis
  template:
    metadata:
      labels:
        app: user-redis
    spec:
      containers:
        - name: user-redis
          image: redis
          ports:
            - containerPort: 6379
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: user-redis
  labels:
    app: user
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: user-redis
